Locales['nl'] = {
  -- Cloakroom
  ['cloakroom'] = 'kleedkamer',
  ['citizen_wear'] = 'burger outfit',
  ['police_wear'] = 'Doe /eup voor politie outfit',
  ['gilet_wear'] = 'Oranje veiligheids vest',
  ['bullet_wear'] = 'kogelvrij vest',
  ['no_outfit'] = 'er is geen outfit die je past!',
  ['open_cloackroom'] = 'druk ~INPUT_CONTEXT~ om je kleding te veranderen ~y~clothes~s~.',
  -- Armory
  ['remove_object'] = 'pak object',
  ['deposit_object'] = 'stop iets terug',
  ['get_weapon'] = 'pak wapen van wapenkamer',
  ['put_weapon'] = 'plaats wapen in wapenkamer',
  ['buy_weapons'] = 'koop wapens',
  ['armory'] = 'kluis',
  ['open_armory'] = 'druk ~INPUT_CONTEXT~ om toegang te krijgen ~y~Armory~s~.',
  ['armory_owned'] = 'bezit',
  ['armory_free'] = 'gratis',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'wapenkamer - koop wapen',
  ['armory_componenttitle'] = 'wapenkamer - wapen toevoegingen',
  ['armory_bought'] = 'je hebt een ~y~%s~s~ gekocht voor ~r~$%s~s~',
  ['armory_money'] = 'je kan dit niet betalen',
  ['armory_hascomponent'] = 'je bezit dit al!',
  ['get_weapon_menu'] = 'wapenkamer - pak wapen',
  ['put_weapon_menu'] = 'wapenkamer - plaats wapen',
  -- Vehicles
  ['vehicle_menu'] = 'voertuig',
  ['vehicle_blocked'] = 'alle mogelijke spawn points zijn geblokkeerd!',
  ['garage_prompt'] = 'druk ~INPUT_CONTEXT~ om toegang te krijgen tot ~y~Vehicle Actions~s~.',
  ['garage_title'] = 'voertuig acties',
  ['garage_stored'] = 'opgeslagen',
  ['garage_notstored'] = 'niet in garage',
  ['garage_storing'] = 'we zijn je voertuig aan het opslaan!.',
  ['garage_has_stored'] = 'het voertuig is opgeslagen',
  ['garage_has_notstored'] = 'geen bezittende voertuigen zijn gevonden in de buurt',
  ['garage_notavailable'] = 'je voertuig is niet opgeslagen.',
  ['garage_blocked'] = 'er is geen beschikbare spawnpoint',
  ['garage_empty'] = 'you dont have any vehicles in your garage.',
  ['garage_released'] = 'je hebt geen toegang tot dit.',
  ['garage_store_nearby'] = 'er is geen dichtbij voertuig.',
  ['garage_storeditem'] = 'open garage',
  ['garage_storeitem'] = 'sla voertuig op in garage',
  ['garage_buyitem'] = 'voertuig winkel',
  ['helicopter_prompt'] = ' druk ~INPUT_CONTEXT~ om toegang te krijgen tot ~y~Helicopter Actions~s~.',
  ['helicopter_notauthorized'] = 'je hebt geen permissie om dit te doen.',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'voertuig winkel',
  ['vehicleshop_confirm'] = 'wil je dit voertuig kopen?',
  ['vehicleshop_bought'] = 'je hebt dit gekocht ~y~%s~s~ voor ~r~$%s~s~',
  ['vehicleshop_money'] = 'je kunt dit niet betalen',
  ['vehicleshop_awaiting_model'] = 'het voertuig is momentaal aan het laden ~g~DOWNLOADING & LOADING~s~ please wait',
  ['confirm_no'] = 'nee',
  ['confirm_yes'] = 'ja',
  -- Service
  ['service_max'] = 'je kan niet in dienst gaan: %s/%s',
  ['service_not'] = 'je kan niet in dienst gaan verander je kleding eerst.',
  ['service_anonunce'] = 'service informatie',
  ['service_in'] = 'je bent in dienst gegaan',
  ['service_in_announce'] = 'operator ~y~%s~s~ is in dienst gegaan!',
  ['service_out'] = 'je bent uit dienst gegaan.',
  ['service_out_announce'] = 'operator ~y~%s~s~ is uit dienst gegaan.',
  -- Action Menu
  ['citizen_interaction'] = 'burger interactie',
  ['vehicle_interaction'] = 'voertuig interactie',
  ['object_spawner'] = 'object Spawner',

  ['id_card'] = 'ID kaart',
  ['search'] = 'doorzoeken',
  ['handcuff'] = 'boeien / onboeien',
  ['drag'] = 'verplaatsen',
  ['put_in_vehicle'] = 'verplaats in voertuig',
  ['out_the_vehicle'] = 'haal uit voertuig',
  ['fine'] = 'boete',
  ['community_service'] = 'Taakstraf',
  ['jail'] = 'Celstraf',
  ['unpaid_bills'] = 'controleer openstaande vacaturen',
  ['license_check'] = 'beheer rijbewijs',
  ['license_revoke'] = 'trek rijbewijs in',
  ['license_revoked'] = 'je ~b~%s~s~ is ~y~ingetrokken~s~!',
  ['licence_you_revoked'] = 'je hebt een ~b~%s~s~ ingetrokken van ~y~%s~s~',
  ['no_players_nearby'] = 'er is geen speler(s) in de buurt!',
  ['being_searched'] = 'je wordt ~y~doorzocht~s~ door de ~b~Politie~s~',
  -- Vehicle interaction
  ['vehicle_info'] = 'voertuig informatie',
  ['pick_lock'] = 'auto openbreken',
  ['vehicle_unlocked'] = 'voertuig ~g~geopend~s~',
  ['no_vehicles_nearby'] = 'er is geen voertuig in de buurt',
  ['impound'] = 'impound voertuig',
  ['impound_prompt'] = 'druk ~INPUT_CONTEXT~ om te annuleren ~y~impound~s~',
  ['impound_canceled'] = 'je hebt de impound geannuleerd',
  ['impound_canceled_moved'] = 'de impound is geannuleerd omdat het voertuig bewoog',
  ['impound_successful'] = 'je hebt het voertuig geimpound',
  ['search_database'] = 'voertuig informatie',
  ['search_database_title'] = 'voertuig informatie - zoek met kenteken plaat',
  ['search_database_error_invalid'] = 'dat is ~r~geen~s~  ~y~echte~s~ kenteken plaat',
  ['search_database_error_not_found'] = 'dat ~y~kenteken plaat~s~ is ~r~niet~s~ geregistreerd aan een voertuig!',
  ['search_database_found'] = 'het voertuig is ~y~geregistreerd~s~ tot ~b~%s~s~',
  -- Traffic interaction
  ['traffic_interaction'] = 'interaction Traffic',
  ['cone'] = 'pion',
  ['barrier'] = 'barrier',
  ['spikestrips'] = 'spijkermat',
  ['box'] = 'doos',
  ['cash'] = 'doos met geld',
  -- ID Card Menu
  ['name'] = 'naam: %s',
  ['job'] = 'baan: %s',
  ['sex'] = 'geslacht: %s',
  ['dob'] = 'DVG: %s',
  ['height'] = 'lengte: %s',
  ['id'] = 'ID: %s',
  ['bac'] = 'BAC: %s',
  ['unknown'] = 'unknown',
  ['male'] = 'man',
  ['female'] = 'vrouw',
  -- Body Search Menu
  ['guns_label'] = '--- wapens ---',
  ['inventory_label'] = '--- Inventory ---',
  ['license_label'] = ' --- Bewijzen ---',
  ['confiscate'] = 'neem in %s',
  ['confiscate_weapon'] = 'neem  %s in met %s kogels',
  ['confiscate_inv'] = 'neem in %sx %s',
  ['confiscate_dirty'] = 'neem in zwartgeld: <span style="color:red;">$%s</span>',
  ['you_confiscated'] = 'je hebt ~y~%sx~s~ ~b~%s~s~ ingenomen van ~b~%s~s~',
  ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ is ingenomen door ~y~%s~s~',
  ['you_confiscated_account'] = 'je hebt ~g~$%s~s~ (%s) ingenomen van ~b~%s~s~',
  ['got_confiscated_account'] = '~g~$%s~s~ (%s) is ingenomen door ~y~%s~s~',
  ['you_confiscated_weapon'] = 'je hebt ~b~%s~s~ ingenomen van ~b~%s~s~ met ~o~%s~s~ kogels',
  ['got_confiscated_weapon'] = 'je ~b~%s~s~ met ~o~%s~s~ kogels is ingenomen door ~y~%s~s~',
  ['traffic_offense'] = 'verkeers overtreding',
  ['minor_offense'] = 'kleine overtreding',
  ['average_offense'] = 'middelmatige overtreding',
  ['major_offense'] = 'grote overtreding',
  ['fine_total'] = 'boete: %s',
  -- Vehicle Info Menu
  ['plate'] = 'nummerplaat: %s',
  ['owner_unknown'] = 'eigenaar: niet bekend',
  ['owner'] = 'eigenaar: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'druk ~INPUT_CONTEXT~ om het menu te openen',
  ['quantity_invalid'] = 'niet het geschikte aantal',
  ['have_withdrawn'] = 'je hebt gepakt ~y~%sx~s~ ~b~%s~s~',
  ['have_deposited'] = 'je hebt terug gestopt ~y~%sx~s~ ~b~%s~s~',
  ['quantity'] = 'aantal',
  ['inventory'] = 'inventory',
  ['police_stock'] = 'politie stock',
  -- Misc
  ['remove_prop'] = 'druk ~INPUT_CONTEXT~ om dit te verwijderen',
  ['map_blip'] = 'Politie Bureau',
  ['unrestrained_timer'] = 'je voelt je handboeien langzamerhand losser worden .',
  -- Notifications
  ['alert_police'] = 'Politie Alert',
  ['phone_police'] = 'Politie',
}

